version: '3'

services:
  frontend:
    build:
      context: ./inquiring-frontend-react/frontend_react_inquiring
      dockerfile: Dockerfile
    ports:
      - 80:80
    restart: always
    depends_on:
      - backend
  db:
      image: postgres:13
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      env_file:
        - ./.env.db
  backend:
    build:
      context: ./backend_drf_inquiring
      dockerfile: Dockerfile.prod
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    restart: always
    depends_on:
      - db

volumes:
  postgres_data:
