# Generated by Django 4.0.2 on 2023-05-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True, max_length=1000, null=True)),
                ('phonnumber', models.BigIntegerField(null=True)),
            ],
        ),
    ]
