# Generated by Django 4.0.2 on 2023-06-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='branch',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
