---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-web
  namespace: addex
  labels:
    app: react-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-web
  template:
    metadata:
      labels:
        app: react-web
    spec:
      initContainers:
      - name: check-api-status
        image: busybox:1.31
        command: [ "sh", "-c" ]
        args:
          - |
            while ! nc -z django-api.addex.svc.cluster.local 8000; do
              echo "Django API service has not started, Waiting ..."
              sleep 6
            done
      containers:
      - name: react-web
        image: 239428837152.dkr.ecr.eu-south-1.amazonaws.com/react-k8s:vd39c795-46
        # image: nginx
        imagePullPolicy: Always
        # resources:
        #   limits:
        #     memory: "500Mi"
        #     cpu: "600m"
        ports:
        - containerPort: 80
        # volumeMounts:
        # - name: react-data
        #   mountPath: /usr/share/nginx/html
      
      # volumes:
      # - name: react-data
      #   persistentVolumeClaim:
      #     claimName: nfs-react-claim

---
apiVersion: v1
kind: Service
metadata:
  name: react-web
  namespace: addex
spec:
  selector:
    app: react-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-react-claim
  namespace: addex
spec:
  storageClassName: efs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Gi