apiVersion: v1
kind: Secret
metadata:
  name: postgresdb-secret
  namespace: addex
type: Opaque
data:
  POSTGRES_USER: ZGphbmdvX3VzZXIK
  POSTGRES_PASSWORD: dDAwckByMDB0Cg==
  POSTGRES_DB: aW5xdWlyeV9kYgo=